### ISSUE TITLE
Thermochimica Install on TACC

### ISSUE THREAD

**Issue by bclayto4UT** [ondrejch/Molten_salt_chemistry#11]
I have been working on a thermochimica install for tacc, but have hit some snags. As I do not have sudo access, I have been trying to use a conda enviorment. However when I go to make the test file, I get these errors.

 -O2 -fno-automatic -fbounds-check -o bin/3phaseDiagramRuPdMo obj/3phaseDiagramRuPdMo.o obj/Thermochimica.o obj/PrintState.o obj/ThermoDebug.o obj/AddPureConPhase.o obj/AddSolnPhase.o obj/ArrowSolver.o obj/Broyden.o obj/CheckAddMisciblePhase.o obj/CheckConvergence.o obj/CheckIterHistory.o obj/CheckMiscibilityGap.o obj/CheckPhaseAssemblage.o obj/CheckPhaseAssemblageID.o obj/CheckPhaseChange.o obj/CheckPureConPhaseAdd.o obj/CheckPureConPhaseRem.o obj/CheckPureConPhaseRemHistory.o obj/CheckSolnPhaseAdd.o obj/CheckSolnPhaseRem.o obj/CheckStagnation.o obj/CheckSysOnlyPureConPhases.o obj/CompChemicalPotential.o obj/CompDrivingForce.o obj/CompExcessGibbsEnergy.o obj/CompExcessGibbsEnergyQKTO.o obj/CompExcessGibbsEnergyRKMP.o obj/CompExcessGibbsEnergySUBG.o obj/CompExcessGibbsEnergySUBI.o obj/CompExcessGibbsEnergySUBL.o obj/CompExcessGibbsEnergySUBM.o obj/CompFunctionNorm.o obj/CompGibbsMagnetic.o obj/CompGibbsMagneticSoln.o obj/CompGibbsMagneticSolnInit.o obj/CompMagneticTemperatureMoment.o obj/CompMolAllSolnPhases.o obj/CompMolFraction.o obj/CompMolSolnPhase.o obj/CompStoichSolnPhase.o obj/CorrectMolFraction.o obj/CorrectPhaseRule.o obj/CorrectStagnation.o obj/GEMDebug.o obj/GEMLineSearch.o obj/GEMNewton.o obj/GEMSolver.o obj/InitGEMSolver.o obj/InitNewPhaseAssemblage.o obj/RemPureConAddSolnPhase.o obj/RemPureConPhase.o obj/RemSolnAddPureConPhase.o obj/RemSolnPhase.o obj/RevertSystem.o obj/ShuffleAssemblage.o obj/SortPick.o obj/Subminimization.o obj/SwapPureConForSolnPhase.o obj/SwapPureConPhase.o obj/SwapSolnForPureConPhase.o obj/SwapSolnPhase.o obj/SwapSolnPhaseSpecific.o obj/ModuleCTZ.o obj/ModuleGEMSolver.o obj/ModuleParseCS.o obj/ModuleReinit.o obj/ModuleSubMin.o obj/ModuleThermo.o obj/ModuleThermoIO.o obj/ParseCSDataBlock.o obj/ParseCSDataBlockGibbs.o obj/ParseCSDataBlockQKTO.o obj/ParseCSDataBlockRKMP.o obj/ParseCSDataBlockSUBG.o obj/ParseCSDataBlockSUBI.o obj/ParseCSDataBlockSUBL.o obj/ParseCSDataBlockSUBM.o obj/ParseCSDataFile.o obj/ParseCSHeader.o obj/ParseCSInterpolationOverrides.o obj/ParseInput3PhaseDiagram.o obj/ParseInput.o obj/ParseInputPhaseDiagram.o obj/CalculateCompositionSUBG.o obj/GibbsEnergy.o obj/HeatCapacity.o obj/PostProcessThermo.o obj/PrintResults.o obj/PrintResultsToFile.o obj/RetryCalculationFirstPhase.o obj/ThermoOutput.o obj/LoadReinitData.o obj/SaveReinitData.o obj/ResetCTZ.o obj/ResetReinit.o obj/ResetThermoAll.o obj/ResetThermo.o obj/ResetThermoParser.o obj/CheckCompounds.o obj/CheckSystemExcess.o obj/CheckSystem.o obj/CheckThermoData.o obj/CheckThermoInput.o obj/CompThermoData.o obj/GetElementName.o obj/GetFirstAssemblage.o obj/GetNewAssemblage.o obj/InitThermo.o obj/LevelingSolver.o obj/MakePhaseExclusionList.o obj/nnls.o obj/PostLevelingSolver.o obj/RandomizeStoichiometry.o obj/CommonTangentZone.o obj/InitCTZ.o obj/CompOtoMRatio.o obj/CouplingUtilities.o obj/CouplingUtilitiesISO_C.o obj/FindSolnSpecies.o obj/GetElementMoleFractionInPhase.o obj/GetElementMolesInPhase.o obj/GetElementNames.o obj/GetOutputChemPot.o obj/GetOutputMolSpecies.o obj/GetOutputMolSpeciesPhase.o obj/GetOutputOinUO2.o obj/GetOutputSiteFraction.o obj/GetOutputSolnSpecies.o obj/GetOutputSpeciesStable.o obj/GetPhaseIndex.o obj/GetPhaseNames.o obj/GetPureConPhaseMol.o obj/GetSolnPhaseMol.o obj/GetSolnSpeciesNames.o obj/GetSUBLMSiteFraction.o obj/GetSUBLMSiteMol.o obj/GetSUBLMStoichSublattice.o obj/GetSUBLSiteFraction.o obj/GetSUBLSiteMol.o obj/GetSUBLStoichSublattice.o obj/MassFunctions.o obj/MQMQAFunctions.o obj/ParseSolnComponent.o obj/WriteJSON.o -L/usr/lib/lapack -llapack -L/usr/lib/libblas -lblas -lgfortran
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__tdelete@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__read_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__libc_fcntl64@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__open64_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__close_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__mprotect@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__nanosleep_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__recv@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__write_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `_IO_enable_locks@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__tfind@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__sigtimedwait@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__twalk@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__tunable_get_val@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__call_tls_dtors@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__libc_pread@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /home1/10220/bclayto4/miniforge/envs/themo2/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libgfortran.so: undefined reference to `clock_gettime@GLIBC_2.2.5'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__tsearch@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__pause_nocancel@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__munmap@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__mmap@GLIBC_PRIVATE'
/home1/10220/bclayto4/miniforge/envs/themo2/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__socket@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
make: *** [Makefile:161: bin/3phaseDiagramRuPdMo] Error 1

**Comment by ondrejch** [comment]
1. compiler and libraries
$ module load gcc/13.2.0 
$ module load mkl

2. Modify makefile:
[..]
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
    # links to lapack and blas libraries:
#    LDLOC   = -L/usr/lib/lapack -llapack -L/usr/lib/libblas -lblas -lgfortran
    # link flags for linux users:
    LDFLAGS = -O2 -fno-automatic -fbounds-check -L${TACC_MKL_LIB} -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread
endif
[..]

**Comment by bclayto4UT** [comment]
This worked! Is there a way to add these modules to the conda environment so that I dont have to load them every time? Sor should I add them to the .bashrc?

**Comment by bclayto4UT** [comment]
Personal note ~, is not a valid path definition, must use /home/[username]/...
