### ISSUE TITLE
Replicating Loc's Work

### ISSUE THREAD

**Issue by bclayto4UT** [ondrejch/Molten_salt_chemistry#12]
This is the error that started the need for a shared Thermochimica instilation on TAC, now that is set up (/corral-secure/utexas/scale_shift/BradenClayton) and I have replicated teh issue I post it here. 

I am not the most familiar with building anything other than having used make or Cmake on occasion. It dosen't seem Loc has the proper files and so I am trying to compile directly by calling something like `g++ *.cpp -o dataProcessor` When I do I get the following error:

Fixes I have Attempted:
1) Removing the function where G_MnF2 is referenced: This resulted in different errors.
2) Compiling individual files one at a time: This fails because of interdependencies.

I wanted to get your thoughts on this before I dive too deep or get Loc involved.

dataProcessor/dataProcessor.cpp:925:56: error: 'G_MnF2' was not declared in this                                                                                         scope; did you mean 'G_NiF2'?
  925 |                         y(18) = aMnF2 - XMn*exp((GF2 - G_MnF2(T))/(R*T))                                                                                        ;
      |                                                        ^~~~~~
      |                                                        G_NiF2
dataProcessor/matrix.cpp: In member function 'Vector& Vector::operator=(std::vec                                                                                        tor<double>&)':
dataProcessor/matrix.cpp:37:13: warning: control reaches end of non-void functio                                                                                        n [-Wreturn-type]
   37 |     array = a;
      |             ^
In file included from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/bits/stl_algobase.h:64,
                 from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/string:51,
                 from dataProcessor/miscellaneous.h:4,
                 from dataProcessor/thermoElectroChem.h:4,
                 from dataProcessor/thermoElectroChem.cpp:1:
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h: In instantiation of 'struct std::pair<const std::                                                                                        __cxx11::basic_string<char>, std::array<double, 9> >':
dataProcessor/thermoElectroChem.h:130:1:   required from here
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:194:11: error: 'std::pair<_T1, _T2>::second' has i                                                                                        ncomplete type
  194 |       _T2 second;                ///< The second member
      |           ^~~~~~
In file included from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/bits/memory_resource.h:47,
                 from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/string:58:
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/tuple:2019:45: note: declaration of 'struct std::array<double, 9>'
 2019 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
In file included from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/bits/char_traits.h:50,
                 from /home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64                                                                                        -conda-linux-gnu/13.3.0/include/c++/string:42:
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits: In substitution of 'template<class _Tp, class ... _Ar                                                                                        gs> using std::__is_constructible_impl = std::__bool_constant<__is_constructible                                                                                        (_Tp, _Args ...)> [with _Tp = std::array<double, 9>; _Args = {const std::array<d                                                                                        ouble, 9>&}]':
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:1045:12:   required from 'struct std::is_constructible                                                                                        <std::array<double, 9>, const std::array<double, 9>&>'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:161:35:   required by substitution of 'template<class                                                                                         ... _Bn> std::__detail::__first_t<std::integral_constant<bool, true>, typename s                                                                                        td::enable_if<(bool)(_Bn::value), void>::type ...> std::__detail::__and_fn(int)                                                                                         [with _Bn = {std::is_constructible<const std::__cxx11::basic_string<char, std::c                                                                                        har_traits<char>, std::allocator<char> >, const std::__cxx11::basic_string<char,                                                                                         std::char_traits<char>, std::allocator<char> >&>, std::is_constructible<std::ar                                                                                        ray<double, 9>, const std::array<double, 9>&>}]'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:177:42:   required from 'struct std::__and_<std::is_co                                                                                        nstructible<const std::__cxx11::basic_string<char, std::char_traits<char>, std::                                                                                        allocator<char> >, const std::__cxx11::basic_string<char, std::char_traits<char>                                                                                        , std::allocator<char> >&>, std::is_constructible<std::array<double, 9>, const s                                                                                        td::array<double, 9>&> >'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:108:45:   required from 'static constexpr bool std                                                                                        ::_PCC<<anonymous>, _T1, _T2>::_ConstructiblePair() [with _U1 = const std::__cxx                                                                                        11::basic_string<char>; _U2 = std::array<double, 9>; bool <anonymous> = true; _T                                                                                        1 = const std::__cxx11::basic_string<char>; _T2 = std::array<double, 9>]'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:554:35:   required by substitution of 'template<cl                                                                                        ass _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && _                                                                                        ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std:                                                                                        :pair<const std::__cxx11::basic_string<char>, std::array<double, 9> >::pair(cons                                                                                        t std::__cxx11::basic_string<char>&, const std::array<double, 9>&) [with _U1 = c                                                                                        onst std::__cxx11::basic_string<char>; _U2 = std::array<double, 9>; typename std                                                                                        ::enable_if<(_ConstructiblePair<_U1, _U2>() && _ImplicitlyConvertiblePair<_U1, _                                                                                        U2>()), bool>::type <anonymous> = <missing>]'
dataProcessor/thermoElectroChem.h:130:1:   required from here
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:1040:25: error: invalid use of incomplete type 'struct                                                                                         std::array<double, 9>' [-fpermissive]
 1040 |       = __bool_constant<__is_constructible(_Tp, _Args...)>;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/tuple:2019:45: note: declaration of 'struct std::array<double, 9>'
 2019 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits: In instantiation of 'struct std::is_constructible<std                                                                                        ::array<double, 9>, const std::array<double, 9>&>':
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:161:35:   required by substitution of 'template<class                                                                                         ... _Bn> std::__detail::__first_t<std::integral_constant<bool, true>, typename s                                                                                        td::enable_if<(bool)(_Bn::value), void>::type ...> std::__detail::__and_fn(int)                                                                                         [with _Bn = {std::is_constructible<const std::__cxx11::basic_string<char, std::c                                                                                        har_traits<char>, std::allocator<char> >, const std::__cxx11::basic_string<char,                                                                                         std::char_traits<char>, std::allocator<char> >&>, std::is_constructible<std::ar                                                                                        ray<double, 9>, const std::array<double, 9>&>}]'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:177:42:   required from 'struct std::__and_<std::is_co                                                                                        nstructible<const std::__cxx11::basic_string<char, std::char_traits<char>, std::                                                                                        allocator<char> >, const std::__cxx11::basic_string<char, std::char_traits<char>                                                                                        , std::allocator<char> >&>, std::is_constructible<std::array<double, 9>, const s                                                                                        td::array<double, 9>&> >'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:108:45:   required from 'static constexpr bool std                                                                                        ::_PCC<<anonymous>, _T1, _T2>::_ConstructiblePair() [with _U1 = const std::__cxx                                                                                        11::basic_string<char>; _U2 = std::array<double, 9>; bool <anonymous> = true; _T                                                                                        1 = const std::__cxx11::basic_string<char>; _T2 = std::array<double, 9>]'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:554:35:   required by substitution of 'template<cl                                                                                        ass _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && _                                                                                        ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std:                                                                                        :pair<const std::__cxx11::basic_string<char>, std::array<double, 9> >::pair(cons                                                                                        t std::__cxx11::basic_string<char>&, const std::array<double, 9>&) [with _U1 = c                                                                                        onst std::__cxx11::basic_string<char>; _U2 = std::array<double, 9>; typename std                                                                                        ::enable_if<(_ConstructiblePair<_U1, _U2>() && _ImplicitlyConvertiblePair<_U1, _                                                                                        U2>()), bool>::type <anonymous> = <missing>]'
dataProcessor/thermoElectroChem.h:130:1:   required from here
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:1048:52: error: static assertion failed: template argu                                                                                        ment must be a complete class or an unbounded array
 1048 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>                                                                                        {}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~                                                                                        ~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:1048:52: note: 'std::__is_complete_or_unbounded<__type                                                                                        _identity<array<double, 9> > >((std::__type_identity<std::array<double, 9> >(),                                                                                         std::__type_identity<std::array<double, 9> >()))' evaluates to false
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits: In instantiation of 'struct std::is_convertible<const                                                                                         std::array<double, 9>&, std::array<double, 9> >':
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:161:35:   required by substitution of 'template<class                                                                                         ... _Bn> std::__detail::__first_t<std::integral_constant<bool, true>, typename s                                                                                        td::enable_if<(bool)(_Bn::value), void>::type ...> std::__detail::__and_fn(int)                                                                                         [with _Bn = {std::is_convertible<const std::__cxx11::basic_string<char, std::cha                                                                                        r_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char,                                                                                         std::char_traits<char>, std::allocator<char> > >, std::is_convertible<const std:                                                                                        :array<double, 9>&, std::array<double, 9> >}]'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:177:42:   required from 'struct std::__and_<std::is_co                                                                                        nvertible<const std::__cxx11::basic_string<char, std::char_traits<char>, std::al                                                                                        locator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>,                                                                                         std::allocator<char> > >, std::is_convertible<const std::array<double, 9>&, std                                                                                        ::array<double, 9> > >'
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:115:43:   required from 'static constexpr bool std                                                                                        ::_PCC<<anonymous>, _T1, _T2>::_ImplicitlyConvertiblePair() [with _U1 = const st                                                                                        d::__cxx11::basic_string<char>; _U2 = std::array<double, 9>; bool <anonymous> =                                                                                         true; _T1 = const std::__cxx11::basic_string<char>; _T2 = std::array<double, 9>]                                                                                        '
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/bits/stl_pair.h:556:43:   required by substitution of 'template<cl                                                                                        ass _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && _                                                                                        ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std:                                                                                        :pair<const std::__cxx11::basic_string<char>, std::array<double, 9> >::pair(cons                                                                                        t std::__cxx11::basic_string<char>&, const std::array<double, 9>&) [with _U1 = c                                                                                        onst std::__cxx11::basic_string<char>; _U2 = std::array<double, 9>; typename std                                                                                        ::enable_if<(_ConstructiblePair<_U1, _U2>() && _ImplicitlyConvertiblePair<_U1, _                                                                                        U2>()), bool>::type <anonymous> = <missing>]'
dataProcessor/thermoElectroChem.h:130:1:   required from here
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/type_traits:1417:30: error: invalid use of incomplete type 'struct                                                                                         std::array<double, 9>' [-fpermissive]
 1417 |     : public __bool_constant<__is_convertible(_From, _To)>
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/tuple:2019:45: note: declaration of 'struct std::array<double, 9>'
 2019 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
dataProcessor/thermoElectroChem.h:130:1: error: could not convert '{{"H2", {0, 1                                                                                        .3068000000000001e+2, 3.3066178000000001e+1, -1.1363417000000001e-2, 1.14328e-5,                                                                                         -2.7728999999999998e-9, 0, -158558, 2.9814999999999998e+2}}, {"HF", {-2.7255000                                                                                        000000001e+2, 1.7378e+2, 3.011693e+1, -3.2466119999999998e-3, 2.8681199999999998                                                                                        e-6, 4.5791400000000001e-10, 0, -24861, 2.9814999999999998e+2}}, {"F2", {0, 2.02                                                                                        78899999999999e+2, 3.14451e+1, 8.4138310000000001e-3, -2.7789000000000002e-6, 2.                                                                                        181e-10, 0, -211175, 2.9814999999999998e+2}}, {"Cr0", {0, 2.3617999999999999e+1,                                                                                         7.4897369999999999e+0, 7.1504979999999996e-2, -9.1675999999999994e-5, 4.6044499                                                                                        999999999e-8, 0, 138157, 2.9814999999999998e+2}}, {"Cr1", {0, 0, 1.846508e+1, 5.                                                                                        4779859999999998e-3, 7.9043300000000003e-6, -1.1477999999999999e-9, 0, 1265791,                                                                                         600}}, {"CrF2", {-7.6469200000000001e+2, 8.6308000000000007e+1, 100, 0, 0, 0, 0,                                                                                         0, 2.9814999999999998e+2}}, {"CrF3", {-1.1252809999999999e+3, 8.305670000000000                                                                                        6e+1, 130, 0, 0, 0, 0, 0, 2.9814999999999998e+2}}, {"Fe0", {0, 2.732100000000000                                                                                        2e+1, 1.842868e+1, 2.464301e-2, -8.9137000000000007e-6, 9.6647099999999994e-9, 0                                                                                        , -12643, 2.9814999999999998e+2}}, {"Fe1", {0, 0, -5.7767650000000001e+4, 1.3791                                                                                        970000000001e+2, -1.227732e-1, 3.8682400000000001e-5, 0, 3.9931e+9, 700}}, {"FeF                                                                                        2", {-6.7454999999999995e+2, 9.2540000000000006e+1, 9.8323999999999998e+1, 0, 0,                                                                                         0, 0, 0, 2.9814999999999998e+2}}, {"FeF30", {-1.0418199999999999e+3, 9.82800000                                                                                        00000001e+1, -2.97945e+4, 1.9268000000000001e+2, -4.6415400000000001e-1, 3.96688                                                                                        99999999998e-4, 0, 2.83084e+8, 2.9814999999999998e+2}}, {"FeF31", {0, 0, 1.54827                                                                                        00000000001e+4, -7.7230900000000005e+1, 1.44403e-1, -9.5453799999999997e-5, 0, -                                                                                        2.38266e+8, 367}}, {"FeF32", {0, 0, 8.6659999999999997e+1, 1.7095599999999999e-2                                                                                        , -2.7940109999999999e-6, 5.8297699999999996e-10, 0, 293204, 450}}, {"Co0", {0,                                                                                         3.007e+1, 1.0994300000000001e+1, 5.4375e-2, -5.5513200000000002e-5, 2.5816999999                                                                                        999999e-8, 0, 164533, 2.9814999999999998e+2}}, {"Co1", {0, 0, -2.045759999999999                                                                                        9e+2, 5.1558199999999998e-1, -4.2154999999999997e-4, 1.29558e-7, 0, 17926700, 70                                                                                        0}}, {"CoF2", {-6.3769000000000005e+2, 8.6239999999999995e+1, 1.0459999999999999                                                                                        e+2, 0, 0, 0, 0, 0, 2.9814999999999998e+2}}, {"CoF3", {-7.9036000000000001e+2, 9                                                                                        .4519999999999996e+1, 1.189327e+2, -4.4705620000000001e-2, 4.0846300000000002e-5                                                                                        , -9.7211069999999992e-9, 0, -1505467, 2.9814999999999998e+2}}, {"Ni0", {0, 2.98                                                                                        70000000000001e+1, 1.3691599999999999e+1, 8.2495089999999993e-2, -1.749549999999                                                                                        9999e-4, 1.6159999999999999e-7, 0, -92417, 2.9814999999999998e+2}}, {"Ni1", {0,                                                                                         0, 1.2480450000000001e+3, -1.2575099999999999e+0, 0, 0, 0, -165126600, 600}}, {"                                                                                        Ni2", {0, 0, 1.6498390000000001e+1, 1.8749129999999999e-2, -6.6398000000000004e-                                                                                        6, 1.7172800000000001e-9, 0, 1872051, 700}}, {"NiF2", {-6.1615499999999997e+2, 7                                                                                        .45e+1, 100, 0, 0, 0, 0, 0, 2.9814999999999998e+2}}, {"Nb", {0, 3.64699999999999                                                                                        99e+1, 2.2014299999999999e+1, 9.88816e-3, -5.6485299999999998e-6, 1.759691000000                                                                                        0001e-9, 0, 21839, 2.9814999999999998e+2}}, {"NbF", {2.3575999999999999e+2, 2.39                                                                                        86000000000001e+2, 3.7845999999999997e+1, 5.4099999999999999e-3, -1.844999999999                                                                                        9999e-6, 3.0449999999999998e-10, 0, -137500, 2.9814999999999998e+2}}, {"NbF2", {                                                                                        -3.3866000000000003e+2, 2.8470999999999998e+2, 6.4462999999999994e+1, -2.33e-3,                                                                                         -3.3210000000000002e-7, 1.7320000000000001e-10, 0, -930200, 2.9814999999999998e+                                                                                        2}}, {"NbF3", {-8.0440999999999997e+2, 3.0025e+2, 1.24879e+2, -2.440000000000000                                                                                        2e-2, 6.7989999999999996e-6, -6.7369999999999996e-10, -2.1354799999999999e+4, 1.                                                                                        931e+6, 2.9814999999999998e+2}}, {"NbF4", {-1.29646e+3, 3.3175999999999999e+2, 1                                                                                        .43667e+2, -1.9179999999999999e-2, 4.4950000000000002e-6, -3.858e-10, -2.1676700                                                                                        000000001e+4, 1.905e+6, 2.9814999999999998e+2}}, {"NbF5", {-1.72025e+3, 3.468600                                                                                        0000000001e+2, 1.21254e+2, 1.5959999999999998e-2, -7.4359999999999996e-6, 1.142e                                                                                        -9, 0, -1.942e+6, 2.9814999999999998e+2}}, {"Nb2F10", {-3.5311599999999999e+3, 5                                                                                        .3491999999999996e+2, 2.61303e+2, 2.9020000000000001e-2, -1.3519999999999999e-5,                                                                                         2.0780000000000001e-9, 0, -4.027e+6, 2.9814999999999998e+2}}, {"Nb3F15", {-5.33                                                                                        48400000000001e+3, 7.3164999999999998e+2, 4.0055000000000001e+2, 4.2750000000000                                                                                        003e-2, -1.9709999999999999e-5, 2.9929999999999999e-9, 0, -5.99e+6, 2.9814999999                                                                                        999998e+2}}, {"Mo", {0, 2.8600000000000001e+1, 2.4727360000000001e+1, 3.96042500                                                                                        00000001e-3, -1.2707059999999999e-6, 1.1530650000000001e-9, 0, -170246, 2.981499                                                                                        9999999998e+2}}, {"MoF4", {-9.4767999999999995e+2, 3.2893000000000001e+2, 8.0138                                                                                        239999999996e+1, 6.3503080000000003e-2, -5.3729249999999997e-5, 1.58591600000000                                                                                        01e-8, 0, -847072, 2.9814999999999998e+2}}, {"MoF5", {-1.2413900000000001e+3, 3.                                                                                        4751999999999998e+2, 1.3269390000000001e+2, 1.224478e-3, -2.0548299999999999e-7,                                                                                         1.4022e-11, 0, -2.767901e+6, 2.9814999999999998e+2}}, {"MoF6", {-1.557660000000                                                                                        0001e+3, 3.5047000000000003e+2, 1.5067920000000001e+2, 6.156463e-3, -1.65776e-6,                                                                                         1.4091099999999999e-10, 0, -2.950587e+6, 2.9814999999999998e+2}}, {"UF3", {-1.5                                                                                        008969999999999e+3, 1.0366e+2, 130, 0, 0, 0, 0, 0, 2.9814999999999998e+2}}, {"UF                                                                                        4", {-1.9146600000000001e+3, 1.1540000000000001e+2, 1.7474000000000001e+2, 0, 0,                                                                                         0, 0, 0, 2.9814999999999998e+2}}}' from '<brace-enclosed initializer list>' to                                                                                         'const std::unordered_map<std::__cxx11::basic_string<char>, std::array<double, 9                                                                                        > >'
  130 | };
      | ^
      | |
      | <brace-enclosed initializer list>
dataProcessor/thermoElectroChem.cpp: In function 'double calc_H(const thermoArra                                                                                        y&, double)':
dataProcessor/thermoElectroChem.cpp:10:20: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   10 |     double H = data[0]*1000;
      |                    ^
dataProcessor/thermoElectroChem.cpp:11:20: error: invalid use of incomplete type                                                                                         'const thermoArray' {aka 'const struct std::array<double, 9>'}
   11 |     double T_ref = data.back();
      |                    ^~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/tuple:2019:45: note: declaration of 'using thermoArray = struct st                                                                                        d::array<double, 9>' {aka 'struct std::array<double, 9>'}
 2019 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
dataProcessor/thermoElectroChem.cpp:12:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   12 |     H += data[2]*(T-T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp:13:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   13 |     H += data[3]*(pow(T,2)-pow(T_ref,2))/2;
      |              ^
dataProcessor/thermoElectroChem.cpp:14:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   14 |     H += data[4]*(pow(T,3)-pow(T_ref,3))/3;
      |              ^
dataProcessor/thermoElectroChem.cpp:15:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   15 |     H += data[5]*(pow(T,4)-pow(T_ref,4))/4;
      |              ^
dataProcessor/thermoElectroChem.cpp:16:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   16 |     H += data[6]*log(T/T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp:17:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   17 |     H -= data[7]*(1/T-1/T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp: In function 'double calc_S(const thermoArra                                                                                        y&, double)':
dataProcessor/thermoElectroChem.cpp:23:20: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   23 |     double S = data[1];
      |                    ^
dataProcessor/thermoElectroChem.cpp:24:20: error: invalid use of incomplete type                                                                                         'const thermoArray' {aka 'const struct std::array<double, 9>'}
   24 |     double T_ref = data.back();
      |                    ^~~~
/home1/10220/bclayto4/miniforge/envs/themo2/lib/gcc/x86_64-conda-linux-gnu/13.3.                                                                                        0/include/c++/tuple:2019:45: note: declaration of 'using thermoArray = struct st                                                                                        d::array<double, 9>' {aka 'struct std::array<double, 9>'}
 2019 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
dataProcessor/thermoElectroChem.cpp:25:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   25 |     S += data[2]*log(T/T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp:26:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   26 |     S += data[3]*(T-T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp:27:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   27 |     S += data[4]*(pow(T,2)-pow(T_ref,2))/2;
      |              ^
dataProcessor/thermoElectroChem.cpp:28:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   28 |     S += data[5]*(pow(T,3)-pow(T_ref,3))/3;
      |              ^
dataProcessor/thermoElectroChem.cpp:29:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   29 |     S -= data[6]*(1/T-1/T_ref);
      |              ^
dataProcessor/thermoElectroChem.cpp:30:14: error: no match for 'operator[]' (ope                                                                                        rand types are 'const thermoArray' {aka 'const std::array<double, 9>'} and 'int'                                                                                        )
   30 |     S -= data[7]*(pow(T,-2)-pow(T_ref,-2))/2;

**Comment by bclayto4UT** [comment]
the files and tool in question are in msr-fission-gas-main/dataProcesor

Locs code is found here [code](https://github.com/lduong1/msr-fission-gas)

**Comment by bclayto4UT** [comment]
This issue was resolved on my personal Computer. I will resolve it on TACC when I next use it. The resolution is explained with #13 . Once this fix has been applied the code can be compiled by running the following command in the dataProcessor Directory: 

`g++ -o dataProcessor.exe *.h *.cpp`

**Comment by bclayto4UT** [comment]
That is not something I have done, but I look forward to learning how! I will update you here once I have.

**Comment by ondrejch** [comment]
https://makefiletutorial.com/

**Comment by bclayto4UT** [comment]
Done, I modified the boilerplate example, seemed to work just fine.
